"use client";

import { useState, useTransition } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { TemplateLibrary } from "./template-library";
import { autoGenerateFromReview } from "@/lib/social-graphics/auto-generate";
import {
  CANVAS_PRESETS,
  type CanvasSize,
  type TemplateId,
} from "@/lib/social-graphics/types";

interface ReviewOption {
  id: string;
  rating: number;
  text: string | null;
  customer_name: string | null;
  source: string;
}

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  reviews: ReviewOption[];
  onGenerated?: (graphicId: string) => void;
}

export function AutoGenerateDialog({
  open,
  onOpenChange,
  reviews,
  onGenerated,
}: AutoGenerateDialogProps) {
  const [selectedReviewId, setSelectedReviewId] = useState<string>("");
  const [selectedTemplateId, setSelectedTemplateId] =
    useState<TemplateId | null>(null);
  const [canvasPresetIndex, setCanvasPresetIndex] = useState<number>(0);
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [step, setStep] = useState<"review" | "template">("review");

  const canvasSize: CanvasSize = CANVAS_PRESETS[canvasPresetIndex];

  const handleGenerate = () => {
    if (!selectedReviewId) return;
    setError(null);

    startTransition(async () => {
      const result = await autoGenerateFromReview({
        reviewId: selectedReviewId,
        templateId: selectedTemplateId ?? undefined,
        canvasSize,
      });

      if (result.success) {
        onOpenChange(false);
        onGenerated?.(result.data.id);
        // Reset
        setSelectedReviewId("");
        setSelectedTemplateId(null);
        setStep("review");
      } else {
        setError(result.error);
      }
    });
  };

  const truncate = (text: string | null, len: number) => {
    if (!text) return "No text";
    return text.length > len ? text.slice(0, len) + "..." : text;
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Generate from Review</DialogTitle>
          <DialogDescription>
            {step === "review"
              ? "Select a review to generate a social graphic"
              : "Choose a template and canvas size"}
          </DialogDescription>
        </DialogHeader>

        {step === "review" && (
          <div className="space-y-3">
            {reviews.length === 0 ? (
              <p className="py-8 text-center text-sm text-muted-foreground">
                No approved reviews available
              </p>
            ) : (
              <div className="max-h-[400px] space-y-2 overflow-y-auto pr-1">
                {reviews.map((review) => (
                  <button
                    key={review.id}
                    type="button"
                    onClick={() => setSelectedReviewId(review.id)}
                    className={`w-full rounded-lg border p-3 text-left transition-colors ${
                      selectedReviewId === review.id
                        ? "border-repwell-teal-300 bg-repwell-teal-300/5"
                        : "border-border hover:border-muted-foreground/30"
                    }`}
                  >
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-xs text-amber-500">
                        {"★".repeat(review.rating)}
                        {"☆".repeat(5 - review.rating)}
                      </span>
                      <span className="text-xs text-muted-foreground">
                        {review.source}
                      </span>
                    </div>
                    <p className="text-sm text-foreground">
                      {truncate(review.text, 120)}
                    </p>
                    <p className="mt-1 text-xs text-muted-foreground">
                      {review.customer_name ?? "Anonymous"}
                    </p>
                  </button>
                ))}
              </div>
            )}
          </div>
        )}

        {step === "template" && (
          <div className="space-y-4">
            {/* Canvas size selector */}
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground">
                Canvas Size
              </label>
              <Select
                value={String(canvasPresetIndex)}
                onValueChange={(v) => setCanvasPresetIndex(Number(v))}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {CANVAS_PRESETS.map((preset, i) => (
                    <SelectItem key={preset.name} value={String(i)}>
                      {preset.name} ({preset.width}x{preset.height})
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Template selection */}
            <TemplateLibrary
              onSelectTemplate={setSelectedTemplateId}
              selectedTemplateId={selectedTemplateId}
            />

            <p className="text-xs text-muted-foreground">
              Leave template unselected to auto-pick the best match
            </p>
          </div>
        )}

        {error && (
          <p className="text-sm text-destructive">{error}</p>
        )}

        <DialogFooter className="gap-2">
          {step === "template" && (
            <Button
              variant="outline"
              onClick={() => setStep("review")}
              disabled={isPending}
            >
              Back
            </Button>
          )}
          {step === "review" ? (
            <Button
              onClick={() => setStep("template")}
              disabled={!selectedReviewId}
            >
              Next
            </Button>
          ) : (
            <Button onClick={handleGenerate} disabled={isPending}>
              {isPending ? "Generating..." : "Generate Graphic"}
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
