"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { TemplateLibrary } from "./template-library";
import { AutoGenerateDialog } from "./auto-generate-dialog";
import { BatchGenerateDialog } from "./batch-generate-dialog";
import { ScheduleDialog } from "./schedule-dialog";
import {
  deleteGraphic,
  duplicateGraphic,
} from "@/lib/social-graphics/actions";
import type { SocialProofGraphic, TemplateId } from "@/lib/social-graphics/types";
import { parseCanvasSize } from "@/lib/social-graphics/types";

interface ReviewOption {
  id: string;
  rating: number;
  text: string | null;
  customer_name: string | null;
  source: string;
}

interface GraphicsListProps {
  graphics: SocialProofGraphic[];
  reviews: ReviewOption[];
}

export function GraphicsList({ graphics, reviews }: GraphicsListProps) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [view, setView] = useState<"list" | "templates">("list");
  const [autoGenOpen, setAutoGenOpen] = useState(false);
  const [batchGenOpen, setBatchGenOpen] = useState(false);
  const [scheduleOpen, setScheduleOpen] = useState(false);

  const handleSelectTemplate = (templateId: TemplateId) => {
    router.push(
      `/dashboard/social-graphics/new?template=${templateId}`
    );
  };

  const handleDelete = (id: string) => {
    startTransition(async () => {
      await deleteGraphic(id);
      router.refresh();
    });
  };

  const handleDuplicate = (id: string) => {
    startTransition(async () => {
      const result = await duplicateGraphic(id);
      if (result.success) {
        router.push(`/dashboard/social-graphics/${result.data.id}`);
      }
    });
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-foreground">
            Social Graphics
          </h1>
          <p className="text-sm text-muted-foreground">
            Create review graphics for social media
          </p>
        </div>
        <div className="flex items-center gap-2">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" size="sm">
                Generate
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem onSelect={() => setAutoGenOpen(true)}>
                From Single Review
              </DropdownMenuItem>
              <DropdownMenuItem onSelect={() => setBatchGenOpen(true)}>
                Batch from Reviews
              </DropdownMenuItem>
              <DropdownMenuItem onSelect={() => setScheduleOpen(true)}>
                Review of the Week
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <Button
            size="sm"
            onClick={() =>
              setView((v) => (v === "list" ? "templates" : "list"))
            }
            variant={view === "templates" ? "secondary" : "outline"}
          >
            {view === "list" ? "Browse Templates" : "View Graphics"}
          </Button>
          <Button
            size="sm"
            onClick={() => router.push("/dashboard/social-graphics/new")}
          >
            New Graphic
          </Button>
        </div>
      </div>

      {/* Templates view */}
      {view === "templates" && (
        <TemplateLibrary
          onSelectTemplate={handleSelectTemplate}
          selectedTemplateId={null}
        />
      )}

      {/* Graphics list view */}
      {view === "list" && (
        <>
          {graphics.length === 0 ? (
            <div className="flex flex-col items-center justify-center rounded-xl border border-dashed py-20">
              <p className="text-sm text-muted-foreground mb-4">
                No graphics yet. Start by choosing a template or generating from
                reviews.
              </p>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setView("templates")}
                >
                  Browse Templates
                </Button>
                <Button size="sm" onClick={() => setAutoGenOpen(true)}>
                  Generate from Review
                </Button>
              </div>
            </div>
          ) : (
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
              {graphics.map((graphic) => {
                const canvasSize = parseCanvasSize(graphic.canvas_size);
                const isScheduled = !!graphic.schedule_cron;

                return (
                  <Card
                    key={graphic.id}
                    className="group relative cursor-pointer overflow-hidden transition-shadow hover:shadow-md"
                    onClick={() =>
                      router.push(`/dashboard/social-graphics/${graphic.id}`)
                    }
                  >
                    <CardContent className="p-0">
                      {/* Preview thumbnail */}
                      <div className="flex h-36 items-center justify-center bg-muted">
                        {graphic.render_url ? (
                          <img
                            src={graphic.render_url}
                            alt={graphic.name}
                            className="h-full w-full object-cover"
                          />
                        ) : (
                          <div className="text-center">
                            <p className="text-xs text-muted-foreground">
                              {canvasSize.width}x{canvasSize.height}
                            </p>
                            {graphic.template_id && (
                              <p className="text-[10px] text-muted-foreground/70 mt-1">
                                {graphic.template_id}
                              </p>
                            )}
                          </div>
                        )}
                      </div>

                      {/* Info */}
                      <div className="p-3">
                        <div className="flex items-center justify-between">
                          <h3 className="text-sm font-medium text-foreground truncate pr-2">
                            {graphic.name}
                          </h3>
                          {isScheduled && (
                            <span className="shrink-0 rounded-full bg-repwell-teal-300/10 px-2 py-0.5 text-[10px] font-medium text-repwell-teal-300">
                              Scheduled
                            </span>
                          )}
                        </div>
                        <p className="text-xs text-muted-foreground mt-1">
                          {new Date(graphic.updated_at).toLocaleDateString()}
                        </p>
                      </div>

                      {/* Actions */}
                      <div className="absolute right-2 top-2 hidden gap-1 group-hover:flex">
                        <button
                          type="button"
                          onClick={(e) => {
                            e.stopPropagation();
                            handleDuplicate(graphic.id);
                          }}
                          disabled={isPending}
                          className="rounded-md bg-background/80 px-2 py-1 text-xs font-medium text-foreground shadow-sm backdrop-blur hover:bg-background"
                        >
                          Duplicate
                        </button>
                        <button
                          type="button"
                          onClick={(e) => {
                            e.stopPropagation();
                            handleDelete(graphic.id);
                          }}
                          disabled={isPending}
                          className="rounded-md bg-destructive/80 px-2 py-1 text-xs font-medium text-white shadow-sm backdrop-blur hover:bg-destructive"
                        >
                          Delete
                        </button>
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          )}
        </>
      )}

      {/* Dialogs */}
      <AutoGenerateDialog
        open={autoGenOpen}
        onOpenChange={setAutoGenOpen}
        reviews={reviews}
        onGenerated={(id) =>
          router.push(`/dashboard/social-graphics/${id}`)
        }
      />
      <BatchGenerateDialog
        open={batchGenOpen}
        onOpenChange={setBatchGenOpen}
        reviews={reviews}
        onGenerated={() => router.refresh()}
      />
      <ScheduleDialog
        open={scheduleOpen}
        onOpenChange={setScheduleOpen}
        onScheduled={() => router.refresh()}
      />
    </div>
  );
}
