/**
 * Review-to-video upsell.
 *
 * After a customer's direct text review is verified and published, we invite
 * them to record a video version of it. This module creates the video
 * testimonial request with the service role (no authed user) and runs the
 * follow-up email sweep used by the cron worker.
 *
 * NOT "use server" on purpose: these helpers are called server-side only
 * (verify-page server action and the cron route).
 */

import { createAdminClient } from "@/lib/supabase/admin";
import { sendReviewVideoUpsellEmail } from "@/lib/email/send";
import { getCelebrationThreshold } from "./public-actions";
import type { Json } from "@/types/database.types";

// =============================================================================
// CONSTANTS
// =============================================================================

/** Days before an upsell video request expires (mirrors createVideoTestimonialRequest) */
const REQUEST_EXPIRY_DAYS = 14;

/** Hours after publish before the follow-up email goes out */
export const UPSELL_MIN_AGE_HOURS = 24;

/** Reviews published longer ago than this are no longer swept */
export const UPSELL_MAX_AGE_HOURS = 72;

/** Maximum reviews processed per sweep */
export const UPSELL_BATCH_LIMIT = 25;

// =============================================================================
// TYPES
// =============================================================================

export interface VideoRequestForReview {
  requestId: string;
  token: string;
  url: string;
  /** False when an existing request for this review was returned instead */
  created: boolean;
}

export interface UpsellSweepResult {
  processed: number;
  sent: number;
  skipped: number;
  failed: number;
  errors: string[];
}

interface UpsellReviewRow {
  id: string;
  user_id: string;
  organization_id: string;
  customer_name: string | null;
  customer_email: string | null;
  rating: number;
  source: string;
  is_published: boolean;
  metadata: Record<string, unknown> | null;
}

// =============================================================================
// REQUEST CREATION
// =============================================================================

function getVideoRequestUrl(token: string): string {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://app.repwell.com";
  return `${baseUrl}/video-testimonial/${token}`;
}

/**
 * Create a video testimonial request for a published direct review.
 *
 * Replicates the insert shape of createVideoTestimonialRequest (actions.ts)
 * minimally: that action is an authed server action with org-access checks,
 * email queueing, and reminder scheduling that do not apply here. The token
 * is generated by the database default, same as the authed path.
 *
 * Idempotent: returns the existing request if one was already created for
 * this review. Returns null when the review is not eligible.
 */
export async function createVideoRequestForReview(params: {
  reviewId: string;
}): Promise<VideoRequestForReview | null> {
  const supabase = createAdminClient();

  // TODO: Remove type assertion after running db:push && db:types
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: review, error } = await (supabase as any)
    .from("reviews")
    .select(
      "id, user_id, organization_id, customer_name, customer_email, rating, source, is_published"
    )
    .eq("id", params.reviewId)
    .maybeSingle();

  if (error || !review) {
    if (error) {
      console.error("Error loading review for video upsell:", error);
    }
    return null;
  }

  const eligible =
    review.source === "direct" && review.is_published && review.customer_email;
  if (!eligible) {
    return null;
  }

  // Idempotency: one upsell request per review
  // TODO: Remove type assertion after running db:push && db:types
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: existing } = await (supabase as any)
    .from("video_testimonial_requests")
    .select("id, token")
    .eq("source_metadata->>review_id", params.reviewId)
    .limit(1)
    .maybeSingle();

  if (existing) {
    return {
      requestId: existing.id,
      token: existing.token,
      url: getVideoRequestUrl(existing.token),
      created: false,
    };
  }

  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + REQUEST_EXPIRY_DAYS);
  const nowIso = new Date().toISOString();

  // TODO: Remove type assertion after running db:push && db:types
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: request, error: insertError } = await (supabase as any)
    .from("video_testimonial_requests")
    .insert({
      organization_id: review.organization_id,
      user_id: review.user_id,
      created_by: null,
      customer_name: review.customer_name || "Customer",
      customer_email: review.customer_email,
      transaction_type: null,
      status: "pending",
      expires_at: expiresAt.toISOString(),
      source: "review_upsell",
      last_transition_at: nowIso,
      last_transition_source: "review_upsell",
      last_transition_reason: "Created from published text review upsell",
      // customer_rating presence matters: the public video flow uses it for
      // quarantine logic on low ratings.
      source_metadata: {
        origin: "review_upsell",
        review_id: review.id,
        customer_rating: review.rating,
      } as Json,
    })
    .select("id, token")
    .single();

  if (insertError || !request) {
    console.error("Failed to create upsell video request:", insertError);
    return null;
  }

  return {
    requestId: request.id,
    token: request.token,
    url: getVideoRequestUrl(request.token),
    created: true,
  };
}

// =============================================================================
// FOLLOW-UP EMAIL SWEEP
// =============================================================================

/** Stamp review metadata so the sweep query stays cheap and idempotent */
async function markReviewUpsellMetadata(
  review: UpsellReviewRow,
  key: "video_upsell_emailed_at" | "video_upsell_skipped_at"
): Promise<void> {
  const supabase = createAdminClient();
  // TODO: Remove type assertion after running db:push && db:types
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { error } = await (supabase as any)
    .from("reviews")
    .update({
      metadata: { ...(review.metadata ?? {}), [key]: new Date().toISOString() },
    })
    .eq("id", review.id);

  if (error) {
    console.error("Failed to mark review upsell metadata:", error);
  }
}

/**
 * Sweep recently published direct reviews and send the video upsell email
 * to customers who have not already received one and have no video request.
 * Called by the review-video-upsell cron route.
 */
export async function sendReviewVideoUpsellEmails(
  batchSize: number = UPSELL_BATCH_LIMIT
): Promise<UpsellSweepResult> {
  const result: UpsellSweepResult = {
    processed: 0,
    sent: 0,
    skipped: 0,
    failed: 0,
    errors: [],
  };

  const supabase = createAdminClient();
  const now = Date.now();
  const newestIso = new Date(now - UPSELL_MIN_AGE_HOURS * 3600_000).toISOString();
  const oldestIso = new Date(now - UPSELL_MAX_AGE_HOURS * 3600_000).toISOString();

  // TODO: Remove type assertion after running db:push && db:types
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: candidates, error } = await (supabase as any)
    .from("reviews")
    .select(
      "id, user_id, organization_id, customer_name, customer_email, rating, source, is_published, metadata"
    )
    .eq("source", "direct")
    .eq("status", "approved")
    .eq("is_published", true)
    .not("customer_email", "is", null)
    .gte("published_at", oldestIso)
    .lte("published_at", newestIso)
    .is("metadata->video_upsell_emailed_at", null)
    .is("metadata->video_upsell_skipped_at", null)
    .order("published_at", { ascending: true })
    .limit(batchSize);

  if (error) {
    result.errors.push(`Failed to load candidate reviews: ${error.message}`);
    return result;
  }

  const reviews = (candidates ?? []) as UpsellReviewRow[];
  const thresholdByOrg = new Map<string, number>();
  const proNameByUser = new Map<string, string | null>();

  for (const review of reviews) {
    result.processed++;
    try {
      // Per-org celebration threshold gates which ratings get the upsell
      let threshold = thresholdByOrg.get(review.organization_id);
      if (threshold === undefined) {
        threshold = await getCelebrationThreshold(review.organization_id);
        thresholdByOrg.set(review.organization_id, threshold);
      }

      if (review.rating < threshold) {
        await markReviewUpsellMetadata(review, "video_upsell_skipped_at");
        result.skipped++;
        continue;
      }

      const request = await createVideoRequestForReview({ reviewId: review.id });
      if (!request) {
        result.failed++;
        result.errors.push(`Review ${review.id}: could not create video request`);
        continue;
      }

      // An existing request means the customer already started the video
      // flow (for example via the verify-page button). Do not email them.
      if (!request.created) {
        await markReviewUpsellMetadata(review, "video_upsell_skipped_at");
        result.skipped++;
        continue;
      }

      let proName = proNameByUser.get(review.user_id);
      if (proName === undefined) {
        const { data: pro } = await supabase
          .from("users")
          .select("full_name")
          .eq("id", review.user_id)
          .maybeSingle();
        proName = pro?.full_name ?? null;
        proNameByUser.set(review.user_id, proName);
      }

      const sendResult = await sendReviewVideoUpsellEmail({
        toEmail: review.customer_email as string,
        toName: review.customer_name ?? undefined,
        organizationId: review.organization_id,
        loanOfficerId: review.user_id,
        reviewId: review.id,
        customerName: review.customer_name ?? undefined,
        professionalName: proName ?? "your professional",
        requestUrl: request.url,
      });

      if (sendResult.success) {
        await markReviewUpsellMetadata(review, "video_upsell_emailed_at");
        result.sent++;
      } else {
        result.failed++;
        result.errors.push(
          `Review ${review.id}: email failed (${sendResult.error ?? "unknown"})`
        );
      }
    } catch (err) {
      result.failed++;
      result.errors.push(
        `Review ${review.id}: ${err instanceof Error ? err.message : "unknown error"}`
      );
    }
  }

  return result;
}
