// This file will be auto-generated by Supabase CLI
// Run: npm run db:types
// For now, this is a placeholder that will be replaced when Supabase is set up

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          domain: string | null;
          logo_url: string | null;
          primary_color: string;
          settings: Json;
          subscription_tier: string;
          subscription_status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          domain?: string | null;
          logo_url?: string | null;
          primary_color?: string;
          settings?: Json;
          subscription_tier?: string;
          subscription_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          domain?: string | null;
          logo_url?: string | null;
          primary_color?: string;
          settings?: Json;
          subscription_tier?: string;
          subscription_status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          organization_id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          role: string;
          is_active: boolean;
          last_login_at: string | null;
          notification_preferences: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          organization_id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role: string;
          is_active?: boolean;
          last_login_at?: string | null;
          notification_preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: string;
          is_active?: boolean;
          last_login_at?: string | null;
          notification_preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      loan_officers: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string | null;
          full_name: string;
          email: string;
          phone: string | null;
          title: string;
          nmls_id: string | null;
          bio: string | null;
          photo_url: string | null;
          branch: string | null;
          region: string | null;
          google_business_id: string | null;
          google_place_id: string | null;
          zillow_profile_url: string | null;
          linkedin_url: string | null;
          average_rating: number;
          total_reviews: number;
          nps_score: number | null;
          reputation_score: number;
          is_active: boolean;
          receive_notifications: boolean;
          auto_request_reviews: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id?: string | null;
          full_name: string;
          email: string;
          phone?: string | null;
          title?: string;
          nmls_id?: string | null;
          bio?: string | null;
          photo_url?: string | null;
          branch?: string | null;
          region?: string | null;
          google_business_id?: string | null;
          google_place_id?: string | null;
          zillow_profile_url?: string | null;
          linkedin_url?: string | null;
          average_rating?: number;
          total_reviews?: number;
          nps_score?: number | null;
          reputation_score?: number;
          is_active?: boolean;
          receive_notifications?: boolean;
          auto_request_reviews?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string | null;
          full_name?: string;
          email?: string;
          phone?: string | null;
          title?: string;
          nmls_id?: string | null;
          bio?: string | null;
          photo_url?: string | null;
          branch?: string | null;
          region?: string | null;
          google_business_id?: string | null;
          google_place_id?: string | null;
          zillow_profile_url?: string | null;
          linkedin_url?: string | null;
          average_rating?: number;
          total_reviews?: number;
          nps_score?: number | null;
          reputation_score?: number;
          is_active?: boolean;
          receive_notifications?: boolean;
          auto_request_reviews?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      surveys: {
        Row: {
          id: string;
          organization_id: string;
          template_id: string;
          loan_officer_id: string;
          customer_name: string;
          customer_email: string;
          customer_phone: string | null;
          transaction_id: string | null;
          transaction_type: string;
          transaction_date: string | null;
          token: string;
          status: string;
          sent_at: string | null;
          opened_at: string | null;
          completed_at: string | null;
          expires_at: string | null;
          reminder_count: number;
          last_reminder_at: string | null;
          source: string;
          source_metadata: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          template_id: string;
          loan_officer_id: string;
          customer_name: string;
          customer_email: string;
          customer_phone?: string | null;
          transaction_id?: string | null;
          transaction_type?: string;
          transaction_date?: string | null;
          token?: string;
          status?: string;
          sent_at?: string | null;
          opened_at?: string | null;
          completed_at?: string | null;
          expires_at?: string | null;
          reminder_count?: number;
          last_reminder_at?: string | null;
          source?: string;
          source_metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          template_id?: string;
          loan_officer_id?: string;
          customer_name?: string;
          customer_email?: string;
          customer_phone?: string | null;
          transaction_id?: string | null;
          transaction_type?: string;
          transaction_date?: string | null;
          token?: string;
          status?: string;
          sent_at?: string | null;
          opened_at?: string | null;
          completed_at?: string | null;
          expires_at?: string | null;
          reminder_count?: number;
          last_reminder_at?: string | null;
          source?: string;
          source_metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          organization_id: string;
          loan_officer_id: string;
          source: string;
          source_review_id: string | null;
          source_url: string | null;
          survey_response_id: string | null;
          rating: number;
          title: string | null;
          text: string | null;
          customer_name: string | null;
          customer_location: string | null;
          sentiment_score: number | null;
          sentiment_label: string | null;
          themes: string[] | null;
          key_phrases: string[] | null;
          status: string;
          approved_at: string | null;
          approved_by: string | null;
          rejection_reason: string | null;
          response_text: string | null;
          response_at: string | null;
          response_by: string | null;
          response_synced_at: string | null;
          is_published: boolean;
          published_at: string | null;
          featured: boolean;
          review_date: string;
          synced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          loan_officer_id: string;
          source: string;
          source_review_id?: string | null;
          source_url?: string | null;
          survey_response_id?: string | null;
          rating: number;
          title?: string | null;
          text?: string | null;
          customer_name?: string | null;
          customer_location?: string | null;
          sentiment_score?: number | null;
          sentiment_label?: string | null;
          themes?: string[] | null;
          key_phrases?: string[] | null;
          status?: string;
          approved_at?: string | null;
          approved_by?: string | null;
          rejection_reason?: string | null;
          response_text?: string | null;
          response_at?: string | null;
          response_by?: string | null;
          response_synced_at?: string | null;
          is_published?: boolean;
          published_at?: string | null;
          featured?: boolean;
          review_date: string;
          synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          loan_officer_id?: string;
          source?: string;
          source_review_id?: string | null;
          source_url?: string | null;
          survey_response_id?: string | null;
          rating?: number;
          title?: string | null;
          text?: string | null;
          customer_name?: string | null;
          customer_location?: string | null;
          sentiment_score?: number | null;
          sentiment_label?: string | null;
          themes?: string[] | null;
          key_phrases?: string[] | null;
          status?: string;
          approved_at?: string | null;
          approved_by?: string | null;
          rejection_reason?: string | null;
          response_text?: string | null;
          response_at?: string | null;
          response_by?: string | null;
          response_synced_at?: string | null;
          is_published?: boolean;
          published_at?: string | null;
          featured?: boolean;
          review_date?: string;
          synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

// Helper types
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
